name: run-unittest
on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run unittest
        run: |
          python3 -m unittest discover -s ./tests -p "test*.py" -q
      - name: Run coverage
        run: |
          coverage run -m unittest discover -s ./tests -p "test*.py" -q
          coverage html -d coverage
          coverage json -o coverage.json
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: .coverage
          path: .coverage
      - name: Publish coverage json
        uses: actions/upload-artifact@v3
        with:
          name: coverage.json
          path: coverage.json
      - name: Publish coverage html
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
